services:
  postgres:
    image: postgres:13
    container_name: url-shortner-postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortner_db
    ports:
      - "25432:5432"
      #- "5432"

 # url-shortener:
    #  image: sakthiece08/url-shortener
    #container_name: url-shortener
      #environment:
      #SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      #SPRING_DATASOURCE_USERNAME: postgres
      #SPRING_DATASOURCE_PASSWORD: postgres
      #ports:
      #- "8090:8090"
    #restart: unless-stopped
      #depends_on:
      #- postgres